### ISSUE TITLE
CLI interface

### ISSUE THREAD

**Issue by mmurushkin** [eyesulu/DENKOVY_RELAY#2]
We need to provide a way to operate relay via command line interface. I propose to parse an argument in denkovy_code.py script that will define what we want to achieve: 

1.  Parse "state" argument (0 by default)
2.  Check if value of "state" is 0 or 1. Revert to "0" in case any other value provided. Issue Error message to log.
3.  Check connection to Denkovi and provide current status of the relay in the log
4.  If state = 1 -> switch relay ON
5.  If state = 0 -> switch relay OFF
6.  Exit nominally

**Comment by eyesulu** [comment]
Added the CLI Interface. To check the current state: --state command, to control the relays: --control 0 or 1 command (check readme file)
