### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by mmurushkin** [eyesulu/DENKOVY_RELAY#3]
Provide exception handler in cases when connection to Denkovi module was unsuccessful. Can we provide additional troubleshooting tips to an user? Check network connection, try to ping Denkovi, ...

**Comment by eyesulu** [comment]
Upon loading the web page, if the denkovi module is not connected the following error message occurs. The IP address and Port are taken from the inifile
<img width="508" alt="Screenshot 2023-07-12 at 11 42 02" src="https://github.com/eyesulu/DENKOVY_RELAY/assets/117209896/05cf3a6e-9e6b-4264-b811-4999de682563">
