### ISSUE TITLE
Defaul arguments 

### ISSUE THREAD

**Issue by mmurushkin** [eyesulu/DENKOVY_RELAY#5]
Defaul arguments for --logdir and --inifile are pointed to 
"/Users/aisulu/Desktop/DENKOVY/DENKOVY_proj"

It is proposed to change it to relative path like "./denkovi.ini" and "./logs/". In this case our app will expect .ini file to be located in the working directory. Same for logs directory.

**Comment by eyesulu** [comment]
changed it to "./denkovi.ini" and "./logs/"
